#!/bin/bash
VERSION=chefdk_1.3.43-1_amd64.deb
# wget https://packages.chef.io/stable/ubuntu/12.04/chefdk_0.19.6-1_amd64.deb
wget https://packages.chef.io/files/stable/chefdk/1.3.43/ubuntu/16.04/$VERSION
dpkg -i "$VERSION"
# echo 'export PATH="/opt/chefdk/embedded/bin:$PATH"' >> $HOME/.bash_profile
# echo 'eval "$(chef shell-init bash)"' >> $HOME/.bash_profile
# source $HOME/.bash_profile
rm "$VERSION"
# rm chefdk_0.19.6-1_amd64.deb
