#!/bin/bash
wget https://packages.chef.io/stable/ubuntu/12.04/chefdk_0.19.6-1_amd64.deb
dpkg -i chefdk_0.19.6-1_amd64.deb
echo 'export PATH="/opt/chefdk/embedded/bin:$PATH"' >> $HOME/.bash_profile
echo 'eval "$(chef shell-init bash)"' >> $HOME/.bash_profile
source $HOME/.bash_profile
