#!/bin/bash
ensure_executed utils
apt-get install -y apt-transport-https ca-certificates lsb_release
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
add-apt-repository "deb https://apt.dockerproject.org/repo ubuntu-$(lsb_release -s -c) main"
echo "deb https://apt.dockerproject.org/repo ubuntu-$(lsb_release) main" | sudo tee /etc/apt/sources.list.d/docker.list
apt-get update
apt-cache policy docker-engine
apt-get install -y linux-image-extra-$(uname -r)
apt-get install -y docker-engine systemd-docker
curl -L "https://github.com/docker/compose/releases/download/1.10.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
systemctl start docker
systemctl enable docker

# wget https://github.com/docker/machine/releases/download/v0.6.0/docker-machine-$(uname -s)-$(uname -m)
# mv docker-machine-Linux-x86_64 docker-machine
# chmod +x docker-machine
# mv docker-machine /usr/local/bin

