#!/bin/bash

export UNAME=root
export HOMEDIR=/root

apps=${@:-"apt-update apt-upgrade utils zsh dotfiles tmux direnv firewall gcloud user-create spacemacs spacemacs-setup apt-cleanup"}

echo "installing $apps"
echo

source helpers/functions
export -f add_attempted
export -f add_executed
export -f has_executed
export -f add_app
export -f add_executed
export -f ensure_executed

export DEBIAN_FRONTEND=noninteractive 
execute install-pre

for app in $apps; do
  execute "$app-pre" || true
done

for app in $apps; do
  execute "$app" || true
  add_app $app
done

for app in $apps; do
  execute "$app-post" || true
done

execute install-post
