#!/bin/bash
# rbenv
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
grep rbenv $(SHELL_PROFILE) || [ $$? -eq 0 ]
echo '------------------------------------------------'
# cat rbenv-sh.txt >> $(SHELL_PROFILE)
# $(MAKE) install_ruby_build

# irb
# see http://velvetpulse.com/2012/11/19/improve-your-ruby-workflow-by-integrating-vim-tmux-pry/
git clone git://github.com/nviennot/irb-config.git ~/.irb
cd ~/.irb && make install

# install ruby version
curl -sSL http://getrbenv.com/install | bash -s -- --rubies 2.1.5 --global-ruby 2.1.5 --plugins sstephenson/ruby-build,sstephenson/rbenv-gem-rehash
#curl -sSL http://getrbenv.com/install | bash -s -- --rubies 2.1.5,2.2.2 --global-ruby 2.2.2 --plugins sstephenson/ruby-build,sstephenson/rbenv-gem-rehash
# rbenv install --list
# rbenv install 2.2.3
rbenv rehash


# NOTE: this has problems, either on linux or mac?
# rbenv install 2.1.5
# rbenv global 2.1.5
# rbenv rehash
