#!/bin/bash

# Provisioners
mkdir -p /usr/share/provisioners/vagrant.d
mkdir -p /usr/share/provisioners/packers
chmod -R a+rwx /usr/share/provisioners

# Packer
mkdir -p ~/.config/packer
#cd ~/.config && git clone https://github.com/mitchellh/packer.git
cd ~/.config/packer && wget https://dl.bintray.com/mitchellh/packer/packer_0.8.6_linux_amd64.zip && unzip packer_0.8.6_linux_amd64.zip && rm packer_0.8.6_linux_amd64.zip
