#!/bin/bash
USERNAME=${USERNAME:-clojure}
pw
uid
gid

useradd -m $USERNAME -p $PW -s /bin/zsh
usermod -aG docker $USERNAME
adduser $USERNAME sudo
echo "sudo ALL=(ALL) ALL" | tee -a /etc/sudoers

install dotfiles, etc
