#!/bin/sh
apt-get install -y \
  autossh \
  autotools-dev \
  build-essential \
  curl \
  exuberant-ctags \
  git \
  golang \
  gosu \
  heirloom-mailx \
  htop \
  ispell \
  jq \
  keychain \
  mercurial \
  module-init-tools \
  mosh \
  ntpdate \
  openssh-server \
  python-software-properties \
  silversearcher-ag \
  software-properties-common \
  sysstat \
  tmux \
  tree \
  unzip \
  wget \
  zlib1g-dev
# httpie
# munin
# monit
# gdebi
# exim4
