#!/bin/sh
apt-get install -y \
  autossh \
  autotools-dev \
  build-essential \
  curl \
  exuberant-ctags \
  git \
  heirloom-mailx \
  htop \
  ispell \
  jq \
  keychain \
  module-init-tools \
  mosh \
  ntpdate \
  openssh-server \
  python-software-properties \
  silversearcher-ag \
  software-properties-common \
  sysstat \
  tree \
  unzip \
  wget \
  zlib1g-dev
# httpie
