#!/bin/bash
apt-get -y install virtualbox vagrant virtualbox-dkms
# required for packer and boxcutter
apt-get install -y virtualbox-guest-additions-iso
wget https://bootstrap.pypa.io/ez_setup.py -O - | python
easy_install pip
