#!/bin/bash
# Re-link
rm -f $HOMEDIR/.vim $HOMEDIR/.vimrc
rm -rf $HOMEDIR/.vim
ln -s ${HOMEDIR}/.config/dotfiles/vim $HOMEDIR/.vim
ln -s ${HOMEDIR}/.config/dotfiles/vim/vimrc $HOMEDIR/.vimrc

echo | vim --not-a-term -c VundleInstall -c quitall
